"""
Django settings for stephenlabs project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
import cloudinary

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-70n##1sdpm4l%l-n!958gty2)tl(x1lypvr9s^-a*awzh%z($j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'blog',
    'contact',
    'lab',
    'csp',

    'widget_tweaks',
    'django.contrib.humanize',
    'tinymce',
    'cloudinary',
    'cloudinary_storage',
]

SITE_ID = 1

SITE_URL = 'http://127.0.0.1:8000'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'csp.middleware.CSPMiddleware',
]

CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'style-src': (
            "'self'",
            "'unsafe-inline'",
            "https://fonts.googleapis.com",
            "https://cdn.jsdelivr.net",
            "https://unpkg.com",
            "https://cdn.tailwindcss.com",
            "https://cdnjs.cloudflare.com",
            "https://cdn.tiny.cloud",
        ),
        'font-src': (
            "'self'",
            "https://fonts.gstatic.com",
            "https://cdn.jsdelivr.net",
            "https://unpkg.com",
            "https://cdn.tailwindcss.com",
        ),
        'script-src': (
            "'self'",
            "'unsafe-inline'",
            "'unsafe-eval'",
            "https://cdn.jsdelivr.net",
            "https://unpkg.com",
            "https://cdn.tailwindcss.com",
            "https://cdnjs.cloudflare.com",
            "https://cdn.tiny.cloud",
        ),
        'img-src': (
            "'self'",
            "data:",
            "blob:",
            "https://res.cloudinary.com",
            "https://images.unsplash.com",
        ),
        'connect-src': (
            "'self'",
            "https://res.cloudinary.com",
            "https://api.cloudinary.com",
            "https://api.tiny.cloud",
        ),
    }
}


ROOT_URLCONF = 'stephenlabs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stephenlabs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'StaticFiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if not DEBUG else
            'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication 
LOGIN_URL = 'signin'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# This part is for SMTP services.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER')



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG = {
    'skin': 'oxide-dark',
    'content_css': 'dark',
    'height': 580,
    'min_height': 400,
    'width': '100%',
    'menubar': 'file edit view insert format tools table help',
    'promotion': False,
    'branding': False,
 
    'plugins': (
        'advlist autolink lists link image charmap'
        'preview anchor searchreplace visualblocks '
        'code fullscreen insertdatetime media table '
        'codesample wordcount autoresize quickbars help'
    ),
 
    'toolbar': (
        'undo redo | blocks fontsizeinput | '
        'bold italic underline strikethrough forecolor backcolor | '
        'alignleft aligncenter alignright alignjustify | '
        'bullist numlist outdent indent | '
        'link image media table codesample | '
        'removeformat code fullscreen | help'
    ),
 
    'toolbar_mode': 'sliding',
 
    'content_style': '''
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap');
        body {
            font-family: 'Inter', Arial, sans-serif;
            font-size: 15px;
            line-height: 1.75;
            background-color: #0D1117;
            color: #C9D1D9;
            padding: 1rem 1.5rem;
            max-width: 100%;
        }
        h1, h2, h3, h4 {
            color: #E6EDF3;
            font-weight: 700;
            letter-spacing: -0.02em;
            line-height: 1.3;
        }
        h2 { border-bottom: 1px solid #21262D; padding-bottom: 0.5rem; }
        p { margin: 0 0 1.25rem; }
        a { color: #2F81F7; }
        code {
            font-family: 'JetBrains Mono', monospace;
            font-size: 0.875em;
            background: #161B22;
            border: 1px solid #21262D;
            padding: 0.125rem 0.375rem;
            border-radius: 4px;
            color: #2F81F7;
        }
        pre {
            background: #161B22 !important;
            border: 1px solid #21262D;
            border-radius: 6px;
            padding: 1rem 1.25rem;
            overflow-x: auto;
        }
        pre code { background: none; border: none; padding: 0; color: #C9D1D9; }
        blockquote {
            border-left: 3px solid #2563EB;
            padding-left: 1rem;
            margin-left: 0;
            color: #7D8590;
            font-style: italic;
        }
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid #21262D; padding: 0.5rem 0.75rem; }
        th { background: #1C2128; color: #C9D1D9; font-size: 0.875rem; }
        img { max-width: 100%; border-radius: 6px; }
    ''',
 
    'codesample_languages': [
        {'text': 'Python', 'value': 'python'},
        {'text': 'JavaScript', 'value': 'javascript'},
        {'text': 'TypeScript', 'value': 'typescript'},
        {'text': 'HTML/XML', 'value': 'markup'},
        {'text': 'CSS', 'value': 'css'},
        {'text': 'Bash', 'value': 'bash'},
        {'text': 'JSON', 'value': 'json'},
        {'text': 'SQL', 'value': 'sql'},
        {'text': 'YAML', 'value': 'yaml'},
        {'text': 'Dockerfile', 'value': 'docker'},
        {'text': 'Solidity', 'value': 'solidity'},
        {'text': 'Rust', 'value': 'rust'},
        {'text': 'Go', 'value': 'go'},
    ],
 
    # ── Upload config ──────────────────────────────────────────────────────
    # Points to your tinymce_upload view — note this matches your lab/urls.py
    # path: path('tinymce-upload/', views.tinymce_upload, name='tinymce_upload')
    # But that view is under the 'lab/' prefix, so the full URL is /lab/tinymce-upload/
    # UNLESS you also registered it at the top level.
    # Check your main urls.py and use whichever matches.
    'images_upload_url': '/lab/tinymce-upload/',
    'automatic_uploads': True,
    'file_picker_types': 'file image media',
 
    # ── FIX: file_picker_callback now sends X-CSRFToken ──────────────────
    # This removes the need for @csrf_exempt on the view entirely.
    'file_picker_callback': '''
    function(callback, value, meta) {
        var input = document.createElement('input');
        input.setAttribute('type', 'file');

        if (meta.filetype === 'image') {
            input.setAttribute('accept', 'image/*');
        } else if (meta.filetype === 'media') {
            input.setAttribute('accept', 'video/*,audio/*');
        } else {
            input.setAttribute('accept', '.pdf,.doc,.docx,.xls,.xlsx');
        }

        input.onchange = function() {
            var file = this.files[0];
            if (!file) return;

            var formData = new FormData();
            formData.append('file', file);

            // Get CSRF token from cookie - more reliable method
            function getCsrfToken() {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.startsWith('csrftoken=')) {
                        return cookie.substring('csrftoken='.length);
                    }
                }
                return '';
            }

            var csrfToken = getCsrfToken();

            fetch('/lab/tinymce-upload/', {
                method: 'POST',
                headers: {
                    'X-CSRFToken': csrfToken
                },
                body: formData
            })
            .then(function(response) {
                if (!response.ok) {
                    return response.json().then(function(data) {
                        throw new Error(data.error || 'Upload failed');
                    });
                }
                return response.json();
            })
            .then(function(data) {
                if (data.location) {
                    if (meta.filetype === 'image') {
                        callback(data.location, { alt: file.name });
                    } else if (meta.filetype === 'media') {
                        callback(data.location);
                    } else {
                        callback(data.location, { text: file.name });
                    }
                } else {
                    console.error('TinyMCE upload error:', data.error || data);
                    alert('Upload failed: ' + (data.error || 'Unknown error'));
                }
            })
            .catch(function(err) {
                console.error('TinyMCE upload failed:', err);
                alert('Upload failed: ' + err.message);
            });
        };

        input.click();
    }
    '''
}

cloudinary.config( 
    cloud_name = config('CLOUD_NAME'),
    api_key = config('API_KEY'),
    api_secret = config('API_SECRET'),
    secure = True
)